@startuml

skinparam sequence {
ArrowColor Black
ActorBorderColor Black
LifeLineBorderColor Black
LifeLineBackgroundColor #A9DCDF

ParticipantBorderColor Black
ParticipantBackgroundColor White
ParticipantFontName Impact
ParticipantFontSize 17
ParticipantFontColor Black

ActorBackgroundColor White
ActorFontColor Black
ActorFontSize 17
ActorFontName Aapex
}

actor       Actor     as A
participant TasksListScreen as TLS
participant AddTaskScreen as ATS
participant TasksViewModel as TVM
participant TaskService as TS
participant LocalDB_Hive as LDBH

A ->> TLS: Dodaj zadanie
activate TLS
TLS ->> ATS: Pokaż ekran, aby dodać zadanie
activate ATS
ATS -> ATS: Dodawanie zadania
ATS ->> TVM : Naciśnij przycisk "wyślij"
deactivate ATS
activate TVM
TVM ->> TS: Wołanie TaskServise
activate TS
TS ->> LDBH: Dodaj zadanie do lokalnej bazy danych
activate LDBH

LDBH -->> TS:
deactivate LDBH
TS -->> TVM
deactivate TS
TVM -->> TLS: Pokaż listę zadań
deactivate TVM
TLS -->> A: Wynik
deactivate TLS


@enduml